### ISSUE TITLE
BUG in win7

### ISSUE THREAD

**Issue by Tailsgamerv1roblox** [Visnalize/win7-simu#105]
A bug I found in win7 simu 1. the app closes out of Anything
2. In theme win10,win8/win8.1,win11, start does not work 
3. But that's all I wanted, tell me, but you can also remove the ads

**Comment by khang-nd** [comment]
Could you please share a video recording for 1 and 2? Was it the web or Android version that has the issue and what are your device specs if it's the latter?

**Comment by Tailsgamerv1roblox** [comment]
Yes I will send a video what is this win7 BUG ok

Em sáb., 4 de mai. de 2024 21:49, Khang ***@***.***> escreveu:
