### ISSUE TITLE
I can`t start windows! I SEE ONLY BIOS  and end! And error AdBlock! I don`t have AdBlock!

### ISSUE THREAD

**Issue by percypoodle** [Visnalize/win7-simu#131]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by khang-nd** [comment]
If you can access the simulator from an incognito browser window, then your browser has an Adblock installed.
