### ISSUE TITLE
I don't use adblock, but it still says that I have it enabled

### ISSUE THREAD

**Issue by lolkinito909** [Visnalize/win7-simu#133]
**Describe the bug**

**To Reproduce**
1. Go to 'Win7 Simu'
2. Click on 'any browser [chrome or internet explorer]'
3. Search something
 
**Expected behavior**

**Screenshots
![Безым2янный](https://github.com/user-attachments/assets/651889fa-d580-4adc-928b-71c8041f98af)

**Desktop (please complete the following information):**
 - OS: [Windows 7]
 - Browser [chrome]
 - Version [6.1]

**Smartphone (please complete the following information):**
 - Device: []
 - OS: []
 - Browser []
 - Version []

**Additional context**

**Comment by khang-nd** [comment]
Please see https://github.com/Visnalize/win7-simu/issues/131#issuecomment-2226851777
