### ISSUE TITLE
Feature Request: SAF for External Files (Android 11+)

### ISSUE THREAD

**Issue by Joro1144** [Visnalize/win7-simu#153]
**Is your feature request related to a problem? Please describe.**
_Yes, the fact that you can't directly access files for the emulator in newer versions of Android._

**Describe the solution you'd like**
_If possible, use a external storage method in order to be able to read the files._

**Describe alternatives you've considered**
_Possibly use the [SAF Framework](https://developer.android.com/guide/topics/providers/document-provider) to able to let the user access it in newer versions of Android 11+?_

**Additional context**
_Termux uses a variant of it for their file structure in order to easily make it readily available for their users._

**Comment by khang-nd** [comment]
You _can_ access external files with the "Upload files here" option from the context menu. Please see refer to this [video](https://youtu.be/AzXjUkhkYt0?si=JBjvRIFRK7tGe2bX).
