### ISSUE TITLE
Windows Media Centre (Beta)

### ISSUE THREAD

**Issue by khang-nd** [Visnalize/win7-simu#177]
- [x] Pause or stop a slide show.
- [x]  Show a mini thumbnail at the bottom left corner when music or a slide show or a video is playing.
- [x] Create slide shows with music.
- [x]  Allow users to add custom search paths for media.
- [x]  WMC needs to be flipped horizontally for languages that are written from right to left (e.g. Arabic).
image
- [x] ~Create music playlists.~
- [x] ~Edit the Now Playing list, i.e. clear the list, remove individual songs, rearrange songs.~
- [x] ~WMC searches for songs at startup so if the user adds more songs while it's opening, WMC will not update the Music Library unless it's restarted. So we might need to keep checking for, like, every 3 seconds for new files? In the original, the file will appear in the library as soon as it's added.~
- [x] ~Delete picture, video, and music.~
- [x] ~Handle rating shortcut.~
- [x]  ~Media Only mode (full-screen mode).~
- [x] ~Favourite Pictures screensaver slide show.~
- [x] ~Play favourite pictures.~
- [x] ~Select individual songs, add them to Now Playing~
- [x] ~Display more categories in the Music Library, i.e. artists, genre, year, album artist, etc.~
- [x] ~Save ratings for individual files and display them.~
- [x] ~Play favourite songs.~
- [x] ~Interact with search results.~
- [x] ~The icons beside the commands at the top of every library.~
- [x] ~Handle right-click, show context menu for every selected item.~

**Comment by Mja79865** [comment]
> * [ ]  Pause or stop a slide show.
> * [ ]   Show a mini thumbnail at the bottom left corner when music or a slide show or a video is playing.
> * [ ]  Create slide shows with music.
> * [ ]   Allow users to add custom search paths for media.
> * [ ]   WMC needs to be flipped horizontally for languages that are written from right to left (e.g. Arabic).
>   image
> * [x]  ~Create music playlists.~
> * [x]  ~Edit the Now Playing list, i.e. clear the list, remove individual songs, rearrange songs.~
> * [x]  ~WMC searches for songs at startup so if the user adds more songs while it's opening, WMC will not update the Music Library unless it's restarted. So we might need to keep checking for, like, every 3 seconds for new files? In the original, the file will appear in the library as soon as it's added.~
> * [x]  ~Delete picture, video, and music.~
> * [x]  ~Handle rating shortcut.~
> * [x]   ~Media Only mode (full-screen mode).~
> * [x]  ~Favourite Pictures screensaver slide show.~
> * [x]  ~Play favourite pictures.~
> * [x]  ~Select individual songs, add them to Now Playing~
> * [x]  ~Display more categories in the Music Library, i.e. artists, genre, year, album artist, etc.~
> * [x]  ~Save ratings for individual files and display them.~
> * [x]  ~Play favourite songs.~
> * [x]  ~Interact with search results.~
> * [x]  ~The icons beside the commands at the top of every library.~
> * [x]  ~Handle right-click, show context menu for every selected item.~

Haddle rating shertcut

**Comment by hohaicongthuan** [comment]
@khang-nd Could you kindly tick off all the remaining items and close this issue as it's been completed? It seems that I cannot do it myself. Except for the `Show a mini thumbnail at the bottom left corner when music or a slide show or a video is playing.` should be marked as ___abandoned___ because I think it's unnecessary for now.

**Comment by khang-nd** [comment]
Done :)
