### ISSUE TITLE
Command prompt bug

### ISSUE THREAD

**Issue by CampingRush11** [Visnalize/win7-simu#21]
Command prompt text is normal font instead of the font used in bios.

1. Go to 'Command prompt'
2. See the text

**Expected behavior**
Text should be same as bios text...

**Desktop (please complete the following information):**
 - OS: Android
 - Browser ...
 - Version ...

**Smartphone (please complete the following information):**
 - Device: Vivo
 - OS: Android 6.0.1
 - Browser ...
 - Version 2.27.0 Win7 simu

**Additional context**
Pls simple fix for the problem...

**Comment by khang-nd** [comment]
Thanks for the report. This is fixed and will be part of 2.28.0.
