### ISSUE TITLE
Weather gadgets don't display the weather anymore they don't even want to connect to the internet please giving the [no internet connection please try again later] and it's not like I'm not connected to the internet cuz I am and everything else works just fine online fix this

### ISSUE THREAD

**Issue by coolboi2007** [Visnalize/win7-simu#34]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by khang-nd** [comment]
Duplicate #29
