### ISSUE TITLE
Crash after 3.0.4 update

### ISSUE THREAD

**Issue by WhiteCoems** [Visnalize/win7-simu#36]
Win 7 Simu is now crashing after the starting windows screen, it keeps on a black screen then crashes.

*No screenshots*

OS: Android 11
Browser: Chrome
Version: 3.0.4, downgraded to 3.0.3

Device: LG K41S
OS: Android 11
RAM: 3 GB
Storage space: 32
CPU: Octa-Core 2.0 Ghz
Processor type: ARM
CPU Cores: 8 

Extra Information: i really wanted to update to 3.0.4, to enable the shadow cursor. but it was unexpected that it would crash everytime it pass the *Starting Windows* screen.

**Comment by khang-nd** [comment]
Can you try reinstalling the app and see if it works? Unfortunately I don't have access to an LG device at the moment to reproduce the issue and attempt a fix, this might take a while to get through.

**Comment by khang-nd** [comment]
@WhiteCoems could you please install the latest version (3.1.0) and let me know if the issue is gone? Thank you in advance.
