### ISSUE TITLE
idk what to put here!

### ISSUE THREAD

**Issue by pidhjer** [Visnalize/win7-simu#38]
![bug](https://github.com/Visnalize/win7-simu/assets/114980083/5aa37817-740a-40a2-97ef-242cfce9878c)
that happened when i opened a command prompt when i applied my theme called "windows 7 blue and white edition". how to fix this?

and yes i am a theme studio beginner

also add linux mint theme, ubuntu theme, bodhi linux theme, and mac os x snow leopard theme

ps. nice windows simulator and can you please add more templates on theme studio? :)

**Comment by khang-nd** [comment]
Hi @pidhjer, thanks for reporting. You can customize the style of that text field with:
```css
#window-cmd .container #input {
  /* your style */
}
```

**Comment by pidhjer** [comment]
okay thank you.
