### ISSUE TITLE
MacOs Startup, MacOs Cursor

### ISSUE THREAD

**Issue by Asoldatos** [Visnalize/win7-simu#40]
**Describe the bug**
Hello visnalize!  I am experiencing an issue. When I'm selecting macOS Theme, the cursor remains windows7 styled. An other issue your community must fix, is the startup sound of the MacOS. The startup sound is wrong! It is the startup sound from a mackintosh (Old Apple Computer)

**To Reproduce**
1. Go to 'Control Panel'
2. Click on 'Personalize'
3. Scroll down and find 'MacOs theme'
4. Restart.
5. Log in back.
6. Hear the sound
7. See the cursor

**Expected behavior**
I want to fix the cursor to be macos styled and the startup sound to be macos styled only on the macos theme.

**Screenshots**
I can't upload a screen shot.

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser [Firefox]
 - Version [22H2]

** Tablet (please complete the following information):**
 - Device: [Samsung SM-T500]
 - OS: [Android]
 - Browser [Chrome, Samsung Internet]
 - Version [12]

**Additional context**
I don't have more explanations.

**Comment by Asoldatos** [comment]
Ok I will provide a link. But can you add macos cursor on the cursor settings in control panel > personalization > Cursor settings?

Link for startup sound: https://www.youtube.com/watch?v=AueY0fhOeWQ

**Comment by Asoldatos** [comment]
Watch this video! It's for an other bug! I will provide a link for the transfer I used.

Link: https://wetransfer.com/downloads/b36702912790be4e62a65bd1bc16cccb20230804182955/23b4ffec978925fa6a45c7367b03b72a20230804182955/5daca0?trk=TRN_TDL_01&utm_campaign=TRN_TDL_01&utm_medium=email&utm_source=sendgrid

**Comment by Asoldatos** [comment]
Oh the transfer expires in 6 days.

**Comment by khang-nd** [comment]
Thanks for the hint, I've stored the video locally, will take a look when I have the time.

**Comment by Asoldatos** [comment]
Are you watched the video? The video says about two or three more bugs!

**Comment by khang-nd** [comment]
> Ok I will provide a link. But can you add macos cursor on the cursor settings in control panel > personalization > Cursor settings?
> 
> Link for startup sound: https://www.youtube.com/watch?v=AueY0fhOeWQ

That audio you shared there sounds really just like the one in Win7 Simu to me, I'm not sure if the "difference" you could tell is that significant to be fixed.

> Watch this video! It's for an other bug! I will provide a link for the transfer I used.
> 
> Link: https://wetransfer.com/downloads/b36702912790be4e62a65bd1bc16cccb20230804182955/23b4ffec978925fa6a45c7367b03b72a20230804182955/5daca0?trk=TRN_TDL_01&utm_campaign=TRN_TDL_01&utm_medium=email&utm_source=sendgrid

Regarding this video recording:
* For the reported minimize/maximize controls bug on MacOS theme, I'm certain that the current behavior is correct: the 🟡 button is minimize and the 🟢 button is restore/maximize.
![image](https://github.com/Visnalize/win7-simu/assets/55619201/51da2011-0e6d-4cd1-b3a8-39655a6939fd)
* For the zoom in/out bug, I confirm that it's an actual bug to be fixed. Could you please help make a separate issue for that instead? This one shall be used to address the MacOS cursor only.

Thank you for reporting and  sharing the video recording.

**Comment by Asoldatos** [comment]
I think the video is fake! I think macos doesn't have a startup sound!

**Comment by Asoldatos** [comment]
Dude, can you reopen it and send me back the video since it is expired and i wanna see what i did again. Ahh nostalgia...
