### ISSUE TITLE
The theme wont work

### ISSUE THREAD

**Issue by Doggyiscool** [Visnalize/win7-simu#47]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by khang-nd** [comment]
Please elaborate more on the issue.

**Comment by Doggyiscool** [comment]
It's just says pls wait

**Comment by khang-nd** [comment]
Please fill out the above template and include as much information as possible, otherwise, it's impossible for me to assist you.

**Comment by Doggyiscool** [comment]
I did it now thank you for your help
