### ISSUE TITLE
internet explorer search used real browser

### ISSUE THREAD

**Issue by samet9999** [Visnalize/win7-simu#82]
![Ekran görüntüsü 2024-01-19 014225](https://github.com/Visnalize/win7-simu/assets/156913291/97d12286-9245-49f2-9188-c38774fdc472)
**Describe the bug**
A clear and concise description of what the bug is.chrome site has stopped

**To Reproduce**
1. Go to 'chrome'
2. Click on 'search bar'
3. type 'any'
4. See error any has stopped

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. windows]
 - Browser [e.g. chrome, edge]
 - Version [e.g. 23h2]

**Smartphone (please complete the following information):**
 - Device: [windows 11 23h2]
 - OS: [windows]
 - Browser [e.g. chrome]
 - Version [e.g. 23h2]

**Additional context**

**Comment by samet9999** [comment]
sorry i download file but this file app has virus i open file i anti virus message i press Download anyway and It says downloading this file again will make you vulnerable.

**Comment by khang-nd** [comment]
That file is just a text file, it's not capable of containing any virus.
