### ISSUE TITLE
chrome error

### ISSUE THREAD

**Issue by samet9999** [Visnalize/win7-simu#83]
**Describe the bug**

**To Reproduce**
1. Go to 'chrome'
2. Click on 'search bar'
3. type 'any'
4. See error has stopped

**Expected behavior**

**Screenshots**
![Ekran görüntüsü 2024-01-19 014225](https://github.com/Visnalize/win7-simu/assets/156913291/67b333ee-b74f-49ed-8df1-c5be5d942374)

**Desktop (please complete the following information):**
 - OS: [e.g. windows ios mac linux]
 - Browser [e.g. chrome, safari microsoft edge firefox yandex opera]
 - Version [e.g. 22 23h2]

**Smartphone (please complete the following information):**
 - Device: [e.g. iphone6/7/8/9/10/11/12/13/14/15/15 pro max android]
 - OS: [e.g. iOS8.1 android 10]
 - Browser [e.g. stock browser, safari chrome google]
 - Version [e.g. 22 17 10]

**Additional context**

**Comment by khang-nd** [comment]
See issue #82

**Comment by samet9999** [comment]
Why? Not 82 83
